language: node_js

sudo: false

node_js:
   - 20
   - 22

cache:
   npm: false
   directories:
      - '~/.pnpm-store'

before_install:
   - corepack enable
   - corepack prepare pnpm@latest-9 --activate
   - pnpm config set store-dir ~/.pnpm-store

install:
   - pnpm install

script:
   - pnpm test
