export const DEFAULT_HAS_UPPERCASE_CHARACTERS = true;
export const DEFAULT_UPPERCASE_CHARACTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
export const DEFAULT_HAS_LOWERCASE_CHARACTERS = true;
export const DEFAULT_LOWERCASE_CHARACTERS = "abcdefghijklmnopqrstuvwxyz";
export const DEFAULT_HAS_SPECIAL_CHARACTERS = false;
export const DEFAULT_SPECIAL_CHARACTERS = "!@#$%&*()=[]{}";
export const DEFAULT_HAS_NUMBER_CHARACTERS = true;
export const DEFAULT_NUMBER_CHARACTERS = "0123456789";
